# Configuration for Travis CI server
# Live instance: https://travis-ci.org/redfish4ktc/maven-soapui-extension-plugin
#
# WARN: please validate this file after modification by visiting http://lint.travis-ci.org/
#
language: java
# default install is mvn install --quiet -DskipTests=true
install: mvn --show-version --errors help:system clean initialize -P declareRepositories
#invoker.streamLogs: we cannot access to log files through Travis web ui, so display everything in the console
script: mvn --show-version --errors clean verify -P declareRepositories,runIT -Dinvoker.streamLogs=true
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
notifications:
  email:
    - red4ktc-github987225@yahoo.fr

cache:
  directories:
  - $HOME/.m2
